apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  PGHOST: "{{ .Values.database.host }}"
  PGPORT: "{{ .Values.database.port }}"
  PGDATABASE: "{{ .Values.database.database }}"
  APP_HOST: "0.0.0.0"
  APP_PORT: "3000"
  APP_TRUST_PROXY: "true"
  APP_REQUEST_ID_HEADER: "x-amzn-trace-id"
  APP_DOMAIN: {{ .Values.host }}
  APP_HTTPS: "true"
