apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.database.credentials.secretArn }}
        objectAlias: databaseCredentials
        jmesPath:
          - path: username
            objectAlias: databaseUsername
          - path: password
            objectAlias: databasePassword
  secretObjects:
    - secretName: {{ .Release.Name }}
      type: Opaque
      data:
        - objectName: databaseUsername
          key: PGUSER
        - objectName: databasePassword
          key: PGPASSWORD
